### ISSUE TITLE
Replace scipy_stats.t.ppf with native pytorch function (get_t_and_critical_t)

### ISSUE THREAD

**Issue by LilithWittmann** [causy-dev/causy#10]
Currently our entire codebase is working based on pytorch - except for this one little function (scipy_stats.t.ppf). 

Which exists only in scipy and the entire world is working based on [>30 year old C Code](https://github.com/scipy/scipy/blob/main/scipy/special/cephes/stdtr.c) so noone needs to implement it again. But we wanna run it on the gpu.

So we should either do a nice fake-implementation [like amazon did it in their gluonts](https://github.com/awslabs/gluonts/blob/eadfceb20eedb28f83e2d4e7c6045bf8a13c4402/src/gluonts/torch/distributions/studentT.py#L43) project. Or we just implement it [properly in pytorch](https://github.com/pytorch/pytorch/issues/26334).

**Comment by this-is-sofia** [comment]
We decided to leave it as it does not take as long as we thought.
